spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bootcamp_2504p"
    username: "postgres"
    password: "Admin1234$"
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
